[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'
# "#6eb52f"
# '#7792E3'

# Background color for the main content area
backgroundColor = "#f0f0f5"
# '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#e0e0ef"
# "#586e75"
# "#e0e0ef"
# '#B9F1C0'

# Color used for almost all text
textColor = "#262730"
# "#fafafa"
# "#262730"
# '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"